/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */
#ifndef WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H
#define WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H

#include <stdbool.h>
#include <stdint.h>

#ifndef WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED
#define WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED

typedef enum waywallen_pause_effect_kind {
    WAYWALLEN_PAUSE_EFFECT_KIND_NONE = 0,
    WAYWALLEN_PAUSE_EFFECT_KIND_BLUR = 1,
} waywallen_pause_effect_kind_t;

typedef struct waywallen_blur_effect_config {
    uint32_t radius;
} waywallen_blur_effect_config_t;

typedef struct waywallen_pause_effect_config {
    waywallen_pause_effect_kind_t kind;
    waywallen_blur_effect_config_t blur;
} waywallen_pause_effect_config_t;

typedef struct waywallen_pause_effect_dynamic_config {
    bool active;
} waywallen_pause_effect_dynamic_config_t;

typedef struct waywallen_presentation_capabilities {
    uint32_t flags;
} waywallen_presentation_capabilities_t;

typedef struct waywallen_presentation_config {
    uint64_t generation;
    waywallen_pause_effect_config_t pause_effect;
} waywallen_presentation_config_t;

typedef struct waywallen_presentation_dynamic_config {
    uint64_t generation;
    uint64_t config_generation;
    waywallen_pause_effect_dynamic_config_t pause_effect;
} waywallen_presentation_dynamic_config_t;

typedef struct waywallen_presentation_snapshot {
    waywallen_presentation_config_t config;
    waywallen_presentation_dynamic_config_t dynamic_config;
} waywallen_presentation_snapshot_t;

#endif /* WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED */

#endif /* WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H */
